title: 开源MCU Core IP 项目
logo: /assets/img/logo.png
description: PODES最完整的技术文档都在这里
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

footer-links:
  email:752855220@qq.com
  github: sunyata000

gitalk:
  clientID: <99b0e931d81456d48cf3>
  clientSecret: <21a5501f4e588e3f133ea94d67e21057e8332dc4>
  repo: <sunyata000.github.io>
  owner: <sunyata000>  
